apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-service-pv
  namespace: k8s-project
  labels:
    type: users-service-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-app-storage-claim
  namespace: k8s-project
  labels:
    type: users-app-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi