# DB for the posts-app

# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-posts-db
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: {{ .Release.Name }}-posts-db-pod

---

# Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-posts-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-posts-db-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-posts-db-pod
    spec:
      containers:
        - name: posts-db-pod-container
          image: postgres:15.2
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-post-db-credentials
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-post-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-post-db-credentials
                  key: password
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
            - name: posts-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: posts-db-init
          configMap:
            name: {{ .Release.Name }}-init-post-db
            items:
              - key: init.sql
                path: init.sql
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-posts-pvc

---

# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-posts-pvc
  namespace: {{ .Values.namespace }}
  labels:
    type: {{ .Release.Name }}-posts-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi