# DBs credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: YWRtaW4= # admin
  password: cm9vdA== # root
  dbname: dXNlcnM=   # users