apiVersion: v1
kind: PersistentVolume
metadata:
  name: posts-db-pv
  namespace: k8s-project
  labels:
    type: posts-db-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data/db/posts"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posts-db-storage-claim
  namespace: k8s-project
  labels:
    type: posts-db-storage-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi